test_anagram (__main__.TestExercice) ... FAIL
test_doubles (__main__.TestExercice) ... ok
test_frequence (__main__.TestExercice) ... ok
test_grades (__main__.TestExercice) ... ok
test_order (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_order (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 19, in test_order
    output = [exercice.order(v) for v in values]
  File "test_exercice.py", line 19, in <listcomp>
    output = [exercice.order(v) for v in values]
  File "/home/runner/work/2021a-c01-ch6-1-exercices-Anneraymond08/2021a-c01-ch6-1-exercices-Anneraymond08/exercice.py", line 11, in order
    num_values = [float(value) for value in values if value.isdigit()]
  File "/home/runner/work/2021a-c01-ch6-1-exercices-Anneraymond08/2021a-c01-ch6-1-exercices-Anneraymond08/exercice.py", line 11, in <listcomp>
    num_values = [float(value) for value in values if value.isdigit()]
AttributeError: 'int' object has no attribute 'isdigit'

======================================================================
FAIL: test_anagram (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 37, in test_anagram
    self.assertEqual(
AssertionError: Lists differ: [None, None] != [True, False]

First differing element 0:
None
True

- [None, None]
+ [True, False] : Erreur dans la v√©rification de l'anagramme

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1, errors=1)
